name: asdeployment
description: A new project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.1
  flutter_launcher_icons: ^0.13.1
  provider: ^6.0.5
  rename: ^2.1.1
  firebase_auth: ^4.10.0
  dio: ^5.3.2
  flutter_vlc_player: ^7.3.0
  url_launcher: ^6.1.14
  flutterwave: ^1.0.3
  better_player: ^0.0.63
  
  flutter_localizations:
    sdk: flutter
  animated_splash_screen: ^1.3.0
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon/logo.png"
    background_color: "#000000"
    theme_color: "#000000"
  windows:
    generate: true
    image_path: "assets/icon/logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon/logo.png"
dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.1.0
  flutter_native_splash: ^2.3.2
flutter_native_splash:
  image: assets/icon/logo.png
  color: "#6062DF"

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
  - assets\images\bbs-logo.png
  - assets\icon\logo.png
  - assets\images\nbs-logo.png
  - assets\images\nbssport-logo.png
  - assets\images\ntv-logo.jfif
  - assets\images\sanyuka-logo.jfif
  - assets\images\brightermondaylogo.webp
  - assets\images\linkedin-logo.webp
  - assets\images\ugjobline-logo.png
  - assets\images\spark-logo.png
  - assets\images\ubc-logo.png
  - assets\images\motiv-logo.jpg
  - assets\images\hiphoplogo.jpg
  - assets\images\africon.jpg
  - assets\images\dlalogo.jpeg
  - assets\images\dfcu_logo.jpeg
  - assets\images\refactory_logo.png
  - assets\images\what-next.jpg

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
